export const careers = [
    "Doctor",
    "Nurse",
    "Veterinarian",
    "Pharmacist",
    "Dentist",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech-Language Pathologist",
    "Software Engineer",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Aerospace Engineer",
    "Computer Scientist",
    "Data Scientist",
    "Teacher",
    "Professor",
    "Librarian",
    "Social Worker",
    "Counselor",
    "Psychologist",
    "Special Education Teacher",
    "Writer",
    "Artist",
    "Actor",
    "Director",
    "Musician",
    "Graphic Designer",
    "Web Designer",
    "Animator",
    "Accountant",
    "Financial Analyst",
    "Business Analyst",
    "Marketing Manager",
    "Sales Manager",
    "Project Manager",
    "Human Resources Manager",
    "Entrepreneur",
    "Biologist",
    "Chemist",
    "Physicist",
    "Geologist",
    "Environmental Scientist",
    "Meteorologist",
    "Astronomer",
    "Marine Biologist",
    "Chef",
    "Pilot",
    "Firefighter",
    "Police Officer",
    "Architect",
    "Interior Designer",
    "Travel Agent",
    "Athlete",
    "Lawyer",
    "Judge",
    "Politician",
    "Historian",
    "Archaeologist",
    "Philosopher",
    "Sociologist",
    "Anthropologist",
    "Meteorologist",
    "Oceanographer",
    "Geographer",
    "Cartographer",
    "Urban Planner",
    "Landscape Architect",
    "Pharmacologist",
    "Toxicologist",
    "Microbiologist",
    "Geneticist",
    "Biochemist",
    "Neurologist",
    "Cardiologist",
    "Oncologist",
    "Surgeon",
    "Pediatrician",
    "Dermatologist",
    "Psychiatrist",
    "Chiropractor",
    "Podiatrist",
    "Optometrist",
    "Audiologist",
    "Registered Dietitian",
    "Athletic Trainer",
    "Massage Therapist",
    "Veterinary Technician",
    "Pharmacy Technician",
    "Medical Assistant",
    "Home Health Aide",
    "Phlebotomist",
    "EMT",
    "Paramedic",
    "Radiologic Technologist",
    "Nuclear Medicine Technologist",
    "Respiratory Therapist",
    "Surgical Technologist",
    "Dental Hygienist",
    "Dental Assistant",
    "Medical Coder",
    "Medical Biller",
    "Health Information Technician",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Aerospace Engineer",
    "Computer Engineer",
    "Software Engineer",
    "Computer Scientist",
    "Data Scientist",
    "Web Developer",
    "Software Developer",
    "Network Engineer",
    "Systems Administrator",
    "Database Administrator",
    "Cybersecurity Analyst",
    "Information Security Analyst",
    "Computer Programmer",
    "Game Developer",
    "UX/UI Designer",
    "Graphic Designer",
    "Web Designer",
    "Animator",
    "Illustrator",
    "Photographer",
    "Videographer",
    "Filmmaker",
    "Director",
    "Actor",
    "Actress",
    "Musician",
    "Singer",
    "Songwriter",
    "Composer",
    "Music Producer",
    "DJ",
    "Music Teacher",
    "Dancer",
    "Choreographer",
    "Writer",
    "Author",
    "Journalist",
    "Reporter",
    "Editor",
    "Copywriter",
    "Screenwriter",
    "Poet",
    "Playwright",
    "Novelist",
    "Teacher",
    "Professor",
    "Educator",
    "Tutor",
    "School Counselor",
    "School Psychologist",
    "Special Education Teacher",
    "Early Childhood Educator",
    "Librarian",
    "Archivist",
    "Museum Curator",
    "Social Worker",
    "Case Manager",
    "Child Protective Services Worker",
    "Mental Health Counselor",
    "Marriage and Family Therapist",
    "Psychologist",
    "Psychiatrist",
    "Therapist",
    "Rehabilitation Counselor",
    "Addiction Counselor",
    "School Counselor",
    "Career Counselor",
    "Life Coach",
    "Accountant",
    "Auditor",
    "Financial Analyst",
    "Investment Banker",
    "Stockbroker",
    "Financial Advisor",
    "Tax Preparer",
    "Budget Analyst",
    "Cost Accountant",
    "Management Accountant",
    "Business Analyst",
    "Market Research Analyst",
    "Marketing Manager",
    "Sales Manager",
    "Product Manager",
    "Project Manager",
    "Operations Manager",
    "Human Resources Manager",
    "Recruiter",
    "Training and Development Specialist",
    "Compensation and Benefits Specialist",
    "Labor Relations Specialist",
    "Entrepreneur",
    "Business Owner",
    "Small Business Owner",
    "Startup Founder",
    "Executive",
    "CEO",
    "CFO",
    "COO",
    "CIO",
    "Lawyer",
    "Attorney",
    "Judge",
    "Prosecutor",
    "Defense Attorney",
    "Paralegal",
    "Legal Assistant",
    "Law Clerk",
    "Politician",
    "Government Official",
    "Diplomat",
    "Public Servant",
    "Civil Servant",
    "Foreign Service Officer",
    "Urban Planner",
    "Landscape Architect",
    "Architect",
    "Interior Designer",
    "Construction Manager",
    "Carpenter",
    "Electrician",
    "Plumber",
    "Painter",
    "Mason",
    "Chef",
    "Cook",
    "Baker",
    "Pastry Chef",
    "Bartender",
    "Waiter",
    "Waitress",
    "Restaurant Manager",
    "Hotel Manager",
    "Travel Agent",
    "Tour Guide",
    "Pilot",
    "Flight Attendant",
    "Air Traffic Controller",
    "Mechanic",
    "Auto Mechanic",
    "Diesel Mechanic",
    "Machinist",
    "Welder",
    "Pipefitter",
    "Sheet Metal Worker",
    "Electrician",
    "Plumber",
    "HVAC Technician",
    "Carpenter",
    "Drywaller",
    "Painter",
    "Mason",
    "Concrete Finisher",
    "Roofer",
    "Glazier",
    "Landscaper",
    "Groundskeeper",
    "Farmer",
    "Rancher",
    "Fisherman",
    "Logger",
    "Miner",
    "Firefighter",
    "Police Officer",
    "Detective",
    "Sheriff",
    "Correctional Officer",
    "Border Patrol Agent",
    "Secret Service Agent",
    "FBI Agent",
    "CIA Agent",
    "Military Officer",
    "Enlisted Personnel",
    "Social Worker",
    "Case Manager",
    "Child Protective Services Worker",
    "Mental Health Counselor",
    "Marriage and Family Therapist",
    "Psychologist",
    "Psychiatrist",
    "Therapist",
    "Rehabilitation Counselor",
    "Addiction Counselor",
    "School Counselor",
    "Career Counselor",
    "Life Coach",
    "Athlete",
    "Coach",
    "Athletic Trainer",
    "Physical Therapist",
    "Occupational Therapist",
    "Chiropractor",
    "Massage Therapist",
    "Personal Trainer",
    "Fitness Instructor",
    "Yoga Instructor",
    "Pilates Instructor",
    "Dancer",
    "Choreographer",
    "Musician",
    "Singer",
    "Songwriter",
    "Composer",
    "Music Producer",
    "DJ",
    "Music Teacher",
    "Actor",
    "Actress",
    "Model",
    "Comedian",
    "Magician",
    "Circus Performer",
    "Artist",
    "Painter",
    "Sculptor",
    "Ceramist",
    "Glassblower",
    "Jeweler",
    "Photographer",
    "Videographer",
    "Filmmaker",
    "Director",
    "Screenwriter",
    "Animator",
    "Graphic Designer",
    "Web Designer",
    "UX/UI Designer",
    "Illustrator",
    "Cartoonist",
    "Architect",
    "Interior Designer",
    "Landscape Architect",
    "Urban"
]